package gosql

import (
	"fmt"
	"strconv"
	"strings"
)

// CodeGenerator 代码生成器，将 AST 编译为纯静态 Go 函数。
// 所有表达式在代码生成阶段编译为原生 Go 代码，运行时不需要解释器。
// define 块编译为独立函数，use 编译为直接函数调用。
type CodeGenerator struct {
	bufs        []*strings.Builder // 缓冲区栈（用于 define 函数生成时切换）
	indent      int
	varCounter  int
	pkgPrefix   string             // "gosql." (外部包) 或 "" (gosql 包内)
	knownKeys   map[string]string  // 模板 key -> 函数名
	funcPrefix  string             // 当前函数名前缀（用于嵌套 define）
	defineFuncs []string           // 收集的 define 函数代码
}

// NewCodeGenerator 创建代码生成器
// pkgPrefix: "gosql." 表示生成代码在外部包（import gosql），"" 表示在 gosql 包内
func NewCodeGenerator(pkgPrefix string) *CodeGenerator {
	return &CodeGenerator{
		pkgPrefix: pkgPrefix,
		knownKeys: make(map[string]string),
	}
}

// GenerateFile 从模板列表生成完整的 Go 源文件
// buildTag 可选，非空时在文件头部添加 //go:build 标签
func (g *CodeGenerator) GenerateFile(templates []*SQLTemplate, asts map[string]*TemplateAST, packageName, sourceFile string, buildTag ...string) (string, error) {
	type funcEntry struct {
		key      string
		funcName string
		code     string
	}

	// 第一步：建立已知模板映射（用于 @use 直接调用）
	for _, tmpl := range templates {
		key := tmpl.Namespace + "." + tmpl.Name
		g.knownKeys[key] = sanitizeFuncName(key)
	}

	var entries []funcEntry
	g.defineFuncs = nil

	// 第二步：为每个模板生成函数
	for _, tmpl := range templates {
		key := tmpl.Namespace + "." + tmpl.Name
		ast, ok := asts[key]
		if !ok {
			continue
		}

		funcName := g.knownKeys[key]

		// 重置状态
		g.bufs = []*strings.Builder{{}}
		g.indent = 1
		g.varCounter = 0
		g.funcPrefix = funcName

		// 生成函数体
		if err := g.generateNodes(ast.Nodes); err != nil {
			return "", fmt.Errorf("generating %s: %w", key, err)
		}

		// 构建完整函数
		var funcCode strings.Builder
		funcCode.WriteString(fmt.Sprintf("func %s(ctx *%sStaticContext) (retErr error) {\n", funcName, g.pkgPrefix))
		funcCode.WriteString("\tdefer ctx.Recover(&retErr)\n\n")
		funcCode.WriteString(g.buf().String())
		funcCode.WriteString("\treturn nil\n")
		funcCode.WriteString("}\n")

		entries = append(entries, funcEntry{
			key:      key,
			funcName: funcName,
			code:     funcCode.String(),
		})
	}

	// 第三步：构建完整文件
	var result strings.Builder
	result.WriteString("// Code generated by gosqlgen. DO NOT EDIT.\n")
	result.WriteString(fmt.Sprintf("// Source: %s\n\n", sourceFile))

	// 可选 build tag
	if len(buildTag) > 0 && buildTag[0] != "" {
		result.WriteString(fmt.Sprintf("//go:build %s\n\n", buildTag[0]))
	}

	result.WriteString(fmt.Sprintf("package %s\n\n", packageName))

	// 导入
	if g.pkgPrefix != "" {
		result.WriteString("import (\n")
		result.WriteString("\t\"github.com/llyb120/gosql\"\n")
		result.WriteString(")\n\n")
	}

	// init 函数（仅注册模板函数，不注册 define）
	result.WriteString("func init() {\n")
	for _, entry := range entries {
		result.WriteString(fmt.Sprintf("\t%sRegisterStatic(%s, %s)\n",
			g.pkgPrefix, strconv.Quote(entry.key), entry.funcName))
	}
	result.WriteString("}\n\n")

	// 输出模板函数
	for _, entry := range entries {
		result.WriteString(entry.code)
		result.WriteString("\n")
	}

	// 输出 define 函数
	for _, defCode := range g.defineFuncs {
		result.WriteString(defCode)
		result.WriteString("\n")
	}

	return result.String(), nil
}

// ==================== 缓冲区管理 ====================

func (g *CodeGenerator) buf() *strings.Builder {
	return g.bufs[len(g.bufs)-1]
}

func (g *CodeGenerator) pushBuf() {
	g.bufs = append(g.bufs, &strings.Builder{})
}

func (g *CodeGenerator) popBuf() string {
	result := g.bufs[len(g.bufs)-1].String()
	g.bufs = g.bufs[:len(g.bufs)-1]
	return result
}

// writeLine 写入一行带缩进的代码
func (g *CodeGenerator) writeLine(format string, args ...interface{}) {
	b := g.buf()
	for i := 0; i < g.indent; i++ {
		b.WriteString("\t")
	}
	if len(args) > 0 {
		b.WriteString(fmt.Sprintf(format, args...))
	} else {
		b.WriteString(format)
	}
	b.WriteString("\n")
}

// ==================== 节点生成 ====================

func (g *CodeGenerator) generateNodes(nodes []Node) error {
	for _, node := range nodes {
		if err := g.generateNode(node); err != nil {
			return err
		}
	}
	return nil
}

func (g *CodeGenerator) generateNode(node Node) error {
	switch n := node.(type) {
	case *TextNode:
		return g.generateText(n)
	case *VarNode:
		return g.generateVar(n)
	case *VarExprNode:
		return g.generateVarExpr(n)
	case *RawNode:
		return g.generateRaw(n)
	case *RawExprNode:
		return g.generateRawExpr(n)
	case *IfNode:
		return g.generateIf(n)
	case *ForNode:
		return g.generateFor(n)
	case *CodeNode:
		return g.generateCode(n)
	case *UseNode:
		return g.generateUse(n)
	case *DefineNode:
		return g.generateDefine(n)
	case *ConditionalLineNode:
		return g.generateConditionalLine(n)
	case *FuncBlockNode:
		return g.generateFuncBlock(n)
	default:
		return fmt.Errorf("unknown node type: %T", node)
	}
}

// ==================== 文本节点 ====================

func (g *CodeGenerator) generateText(n *TextNode) error {
	if n.Text == "" {
		return nil
	}
	g.writeLine("ctx.WriteSQL(%s)", strconv.Quote(n.Text))
	return nil
}

// ==================== 变量节点 @var ====================

func (g *CodeGenerator) generateVar(n *VarNode) error {
	if n.Conditional {
		g.varCounter++
		v := fmt.Sprintf("_v%d", g.varCounter)
		ok := fmt.Sprintf("_ok%d", g.varCounter)
		g.writeLine("{")
		g.indent++
		g.writeLine("%s, %s := ctx.Get(%s)", v, ok, strconv.Quote(n.Name))
		g.writeLine("if !%s || !%sToBool(%s) {", ok, g.pkgPrefix, v)
		g.indent++
		g.writeLine("ctx.SkipCurrentLine()")
		g.indent--
		g.writeLine("} else {")
		g.indent++
		g.writeLine("ctx.AppendArg(%s)", v)
		g.indent--
		g.writeLine("}")
		g.indent--
		g.writeLine("}")
	} else {
		g.writeLine("ctx.AppendArg(ctx.MustGet(%s))", strconv.Quote(n.Name))
	}
	return nil
}

// ==================== 变量表达式节点 @{ expr } ====================

func (g *CodeGenerator) generateVarExpr(n *VarExprNode) error {
	exprCode, err := CompileValueExprToGo(n.Expr, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("compile var expr %q: %w", n.Expr, err)
	}

	if n.Conditional {
		g.varCounter++
		v := fmt.Sprintf("_v%d", g.varCounter)
		g.writeLine("{")
		g.indent++
		g.writeLine("%s := %s", v, exprCode)
		g.writeLine("if !%sToBool(%s) {", g.pkgPrefix, v)
		g.indent++
		g.writeLine("ctx.SkipCurrentLine()")
		g.indent--
		g.writeLine("} else {")
		g.indent++
		g.writeLine("ctx.AppendArg(%s)", v)
		g.indent--
		g.writeLine("}")
		g.indent--
		g.writeLine("}")
	} else {
		g.writeLine("ctx.AppendArg(%s)", exprCode)
	}
	return nil
}

// ==================== 直接输出变量 @=var ====================

func (g *CodeGenerator) generateRaw(n *RawNode) error {
	if n.Conditional {
		g.varCounter++
		v := fmt.Sprintf("_v%d", g.varCounter)
		ok := fmt.Sprintf("_ok%d", g.varCounter)
		g.writeLine("{")
		g.indent++
		g.writeLine("%s, %s := ctx.Get(%s)", v, ok, strconv.Quote(n.Name))
		g.writeLine("if !%s || !%sToBool(%s) {", ok, g.pkgPrefix, v)
		g.indent++
		g.writeLine("ctx.SkipCurrentLine()")
		g.indent--
		g.writeLine("} else {")
		g.indent++
		g.writeLine("ctx.AppendRaw(%s)", v)
		g.indent--
		g.writeLine("}")
		g.indent--
		g.writeLine("}")
	} else {
		g.writeLine("ctx.AppendRaw(ctx.MustGet(%s))", strconv.Quote(n.Name))
	}
	return nil
}

// ==================== 直接输出表达式 @={expr} ====================

func (g *CodeGenerator) generateRawExpr(n *RawExprNode) error {
	exprCode, err := CompileValueExprToGo(n.Expr, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("compile raw expr %q: %w", n.Expr, err)
	}

	if n.Conditional {
		g.varCounter++
		v := fmt.Sprintf("_v%d", g.varCounter)
		g.writeLine("{")
		g.indent++
		g.writeLine("%s := %s", v, exprCode)
		g.writeLine("if !%sToBool(%s) {", g.pkgPrefix, v)
		g.indent++
		g.writeLine("ctx.SkipCurrentLine()")
		g.indent--
		g.writeLine("} else {")
		g.indent++
		g.writeLine("ctx.AppendRaw(%s)", v)
		g.indent--
		g.writeLine("}")
		g.indent--
		g.writeLine("}")
	} else {
		g.writeLine("ctx.AppendRaw(%s)", exprCode)
	}
	return nil
}

// ==================== if 节点 ====================

func (g *CodeGenerator) generateIf(n *IfNode) error {
	// 编译主条件
	condCode, err := CompileConditionToGo(n.Condition, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("compile if condition %q: %w", n.Condition, err)
	}

	g.writeLine("{")
	g.indent++

	g.varCounter++
	doneVar := fmt.Sprintf("_done%d", g.varCounter)
	g.writeLine("%s := false", doneVar)

	// 主 if 分支
	g.writeLine("if %s {", condCode)
	g.indent++
	if err := g.generateNodes(n.Body); err != nil {
		return err
	}
	g.writeLine("%s = true", doneVar)
	g.indent--
	g.writeLine("}")

	// else if 分支
	for _, elseIf := range n.ElseIf {
		elseCondCode, err := CompileConditionToGo(elseIf.Condition, g.pkgPrefix)
		if err != nil {
			return fmt.Errorf("compile else if condition %q: %w", elseIf.Condition, err)
		}
		g.writeLine("if !%s && %s {", doneVar, elseCondCode)
		g.indent++
		if err := g.generateNodes(elseIf.Body); err != nil {
			return err
		}
		g.writeLine("%s = true", doneVar)
		g.indent--
		g.writeLine("}")
	}

	// else 分支
	if n.Else != nil {
		g.writeLine("if !%s {", doneVar)
		g.indent++
		if err := g.generateNodes(n.Else.Body); err != nil {
			return err
		}
		g.indent--
		g.writeLine("}")
	}

	g.indent--
	g.writeLine("}")
	return nil
}

// ==================== for 节点 ====================

func (g *CodeGenerator) generateFor(n *ForNode) error {
	expr := strings.TrimSpace(n.Expr)
	if strings.Contains(expr, "range") {
		return g.generateForRange(n)
	}
	return g.generateForTraditional(n)
}

// generateForRange 生成 range 循环（编译为 gosql.Range + 闭包）
func (g *CodeGenerator) generateForRange(n *ForNode) error {
	info, err := ParseForRange(n.Expr, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("parse for range %q: %w", n.Expr, err)
	}

	g.varCounter++
	errVar := fmt.Sprintf("_forErr%d", g.varCounter)
	idxVar := fmt.Sprintf("_idx%d", g.varCounter)
	valVar := fmt.Sprintf("_val%d", g.varCounter)

	g.writeLine("if %s := %sRange(%s, func(%s, %s interface{}) error {",
		errVar, g.pkgPrefix, info.RangeCode, idxVar, valVar)
	g.indent++

	// 设置循环变量
	if info.IndexVar != "_" && info.IndexVar != "" {
		g.writeLine("ctx.Set(%s, %s)", strconv.Quote(info.IndexVar), idxVar)
	}
	if info.ValueVar != "_" && info.ValueVar != "" {
		g.writeLine("ctx.Set(%s, %s)", strconv.Quote(info.ValueVar), valVar)
	}

	// 生成循环体
	if err := g.generateNodes(n.Body); err != nil {
		return err
	}

	g.writeLine("return nil")
	g.indent--
	g.writeLine("}); %s != nil { return %s }", errVar, errVar)
	return nil
}

// generateForTraditional 生成传统 for 循环（编译为原生 Go for 循环）
func (g *CodeGenerator) generateForTraditional(n *ForNode) error {
	expr := strings.TrimSpace(n.Expr)
	parts := strings.Split(expr, ";")
	if len(parts) != 3 {
		return fmt.Errorf("invalid for expression: %s", expr)
	}

	initPart := strings.TrimSpace(parts[0])
	condPart := strings.TrimSpace(parts[1])
	postPart := strings.TrimSpace(parts[2])

	// 解析 init: i := 0
	initInfo, err := ParseForInit(initPart, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("parse for init: %w", err)
	}

	// 编译条件: i < 10
	condCode, err := CompileConditionToGo(condPart, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("compile for condition %q: %w", condPart, err)
	}

	// 解析 post: i++
	postInfo, err := ParseForPost(postPart, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("parse for post: %w", err)
	}

	g.writeLine("{")
	g.indent++

	// 初始化
	g.writeLine("ctx.Set(%s, %s)", strconv.Quote(initInfo.VarName), initInfo.ValueCode)

	// for 循环
	g.writeLine("for %s {", condCode)
	g.indent++

	// 循环体
	if err := g.generateNodes(n.Body); err != nil {
		return err
	}

	// 后置语句
	g.writeLine("ctx.Set(%s, %s)", strconv.Quote(postInfo.VarName), postInfo.Code)

	g.indent--
	g.writeLine("}")

	g.indent--
	g.writeLine("}")
	return nil
}

// ==================== 代码块 @{} ====================

func (g *CodeGenerator) generateCode(n *CodeNode) error {
	// @{} 块作为回退机制，使用解释器
	g.varCounter++
	errVar := fmt.Sprintf("_codeErr%d", g.varCounter)
	g.writeLine("if %s := ctx.ExecCode(%s); %s != nil { return %s }",
		errVar, strconv.Quote(n.Code), errVar, errVar)
	return nil
}

// ==================== use 节点 ====================

func (g *CodeGenerator) generateUse(n *UseNode) error {
	g.writeLine("{")
	g.indent++

	// 生成 covers 映射
	g.varCounter++
	coversVar := fmt.Sprintf("_covers%d", g.varCounter)
	g.writeLine("%s := make(map[string]func(*%sStaticContext) error)", coversVar, g.pkgPrefix)

	for _, cover := range n.Covers {
		g.varCounter++
		coverFnVar := fmt.Sprintf("_coverFn%d", g.varCounter)
		g.writeLine("%s := func(ctx *%sStaticContext) error {", coverFnVar, g.pkgPrefix)
		g.indent++
		if err := g.generateNodes(cover.Body); err != nil {
			return err
		}
		g.writeLine("return nil")
		g.indent--
		g.writeLine("}")
		g.writeLine("%s[%s] = %s", coversVar, strconv.Quote(cover.Name), coverFnVar)
	}

	// 检查目标是否在同一生成文件中，如果是，直接函数调用
	targetFunc, isKnown := g.resolveUsePath(n.Path)

	g.varCounter++
	oldCoversVar := fmt.Sprintf("_oldCovers%d", g.varCounter)
	g.writeLine("%s := ctx.SwapCovers(%s)", oldCoversVar, coversVar)

	if isKnown {
		// 直接函数调用（全静态）
		g.varCounter++
		errVar := fmt.Sprintf("_useErr%d", g.varCounter)
		g.writeLine("if %s := %s(ctx); %s != nil { ctx.SwapCovers(%s); return %s }",
			errVar, targetFunc, errVar, oldCoversVar, errVar)
	} else {
		// 回退到 UseTemplate（可能走动态）
		g.varCounter++
		errVar := fmt.Sprintf("_useErr%d", g.varCounter)
		g.writeLine("if %s := ctx.UseTemplate(%s, %s); %s != nil { ctx.SwapCovers(%s); return %s }",
			errVar, strconv.Quote(n.Path), coversVar, errVar, oldCoversVar, errVar)
	}

	g.writeLine("ctx.SwapCovers(%s)", oldCoversVar)

	g.indent--
	g.writeLine("}")
	return nil
}

// resolveUsePath 解析 @use 路径，返回目标函数名（如果在同一生成文件中）
func (g *CodeGenerator) resolveUsePath(path string) (string, bool) {
	parts := strings.Split(path, ".")
	if len(parts) < 2 {
		return "", false
	}

	baseKey := parts[0] + "." + parts[1]
	baseFuncName, ok := g.knownKeys[baseKey]
	if !ok {
		return "", false
	}

	if len(parts) == 2 {
		return baseFuncName, true
	}

	// 嵌套 define: test.sql4.a → _gosql_static_test_sql4__a
	funcName := baseFuncName
	for _, defName := range parts[2:] {
		funcName += "__" + sanitizeName(defName)
	}
	return funcName, true
}

// ==================== define 节点 ====================
// define 编译为独立的顶层函数，通过直接调用组合

func (g *CodeGenerator) generateDefine(n *DefineNode) error {
	// 函数名
	defFuncName := g.funcPrefix + "__" + sanitizeName(n.Name)

	// 在当前函数中生成调用
	g.varCounter++
	errVar := fmt.Sprintf("_defErr%d", g.varCounter)
	g.writeLine("if %s := %s(ctx); %s != nil { return %s }", errVar, defFuncName, errVar, errVar)

	// 切换到新缓冲区生成 define 函数
	g.pushBuf()
	savedIndent := g.indent
	savedCounter := g.varCounter
	savedPrefix := g.funcPrefix

	g.indent = 1
	g.varCounter = 0
	g.funcPrefix = defFuncName

	// define 函数体
	g.writeLine("_fullPath := ctx.PushDefine(%s)", strconv.Quote(n.Name))
	g.writeLine("defer ctx.PopDefine()")

	// 检查 cover
	g.varCounter++
	coverFnVar := fmt.Sprintf("_coverFn%d", g.varCounter)
	g.writeLine("if %s := ctx.GetCover(_fullPath, %s); %s != nil {",
		coverFnVar, strconv.Quote(n.Name), coverFnVar)
	g.indent++
	g.writeLine("return %s(ctx)", coverFnVar)
	g.indent--
	g.writeLine("}")

	// 默认内容
	if err := g.generateNodes(n.Body); err != nil {
		// 恢复状态
		g.popBuf()
		g.indent = savedIndent
		g.varCounter = savedCounter
		g.funcPrefix = savedPrefix
		return err
	}

	// 收集 define 函数
	body := g.popBuf()
	g.indent = savedIndent
	g.varCounter = savedCounter
	g.funcPrefix = savedPrefix

	var funcCode strings.Builder
	funcCode.WriteString(fmt.Sprintf("func %s(ctx *%sStaticContext) error {\n", defFuncName, g.pkgPrefix))
	funcCode.WriteString(body)
	funcCode.WriteString("\treturn nil\n")
	funcCode.WriteString("}\n")

	g.defineFuncs = append(g.defineFuncs, funcCode.String())
	return nil
}

// ==================== 条件行节点 ====================

func (g *CodeGenerator) generateConditionalLine(n *ConditionalLineNode) error {
	condCode, err := CompileConditionToGo(n.Condition, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("compile conditional line %q: %w", n.Condition, err)
	}

	g.writeLine("if %s {", condCode)
	g.indent++
	if err := g.generateNodes(n.LineNodes); err != nil {
		return err
	}
	g.indent--
	g.writeLine("}")
	return nil
}

// ==================== 函数块节点 @func() {} ====================

func (g *CodeGenerator) generateFuncBlock(n *FuncBlockNode) error {
	// 解析函数表达式
	funcInfo, err := ParseFuncCallExpr(n.FuncExpr, g.pkgPrefix)
	if err != nil {
		return fmt.Errorf("parse func block expr %q: %w", n.FuncExpr, err)
	}

	g.writeLine("{")
	g.indent++

	// 保存外层 ctx，用子上下文遮蔽 ctx 变量名
	// 这样 body 中的 ctx.WriteSQL / ctx.AppendArg 等调用自然写入子上下文
	g.varCounter++
	outerCtxVar := fmt.Sprintf("_outerCtx%d", g.varCounter)
	g.writeLine("%s := ctx", outerCtxVar)
	g.writeLine("ctx = %s.SubContext()", outerCtxVar)

	// 生成 body（此时 ctx 已指向子上下文，body 中的 ctx 调用都写入子上下文）
	if err := g.generateNodes(n.Body); err != nil {
		return err
	}

	// 构建查询
	g.varCounter++
	queryVar := fmt.Sprintf("_query%d", g.varCounter)
	g.writeLine("%s := ctx.BuildPtr()", queryVar)

	// 恢复外层 ctx
	g.writeLine("ctx = %s", outerCtxVar)

	// 调用函数块
	argsStr := ""
	if len(funcInfo.Args) > 0 {
		argsStr = ", " + strings.Join(funcInfo.Args, ", ")
	}
	g.writeLine("ctx.CallFuncBlock(%s, %s%s)", strconv.Quote(funcInfo.FuncName), queryVar, argsStr)

	// 将结果写入当前上下文
	g.writeLine("ctx.WriteQuery(%s)", queryVar)

	g.indent--
	g.writeLine("}")
	return nil
}

// ==================== 辅助函数 ====================

// sanitizeFuncName 将模板 key 转换为合法的 Go 函数名
func sanitizeFuncName(key string) string {
	name := strings.ReplaceAll(key, ".", "_")
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, " ", "_")
	return "_gosql_static_" + name
}

// sanitizeName 清理名称（用于 define 函数名后缀）
func sanitizeName(name string) string {
	name = strings.ReplaceAll(name, ".", "_")
	name = strings.ReplaceAll(name, "-", "_")
	name = strings.ReplaceAll(name, " ", "_")
	return name
}
