// Code generated by gosqlgen. DO NOT EDIT.
// Source: example.md

package gosql

func init() {
	RegisterStatic("test.sql1", _gosql_static_test_sql1)
	RegisterStatic("test.sql2", _gosql_static_test_sql2)
	RegisterStatic("test.sql3", _gosql_static_test_sql3)
	RegisterStatic("test.sql4", _gosql_static_test_sql4)
	RegisterStatic("test.sql5", _gosql_static_test_sql5)
	RegisterStatic("test.sql6", _gosql_static_test_sql6)
	RegisterStatic("test.sql7", _gosql_static_test_sql7)
	RegisterStatic("test.sql7_5", _gosql_static_test_sql7_5)
	RegisterStatic("test.sql8", _gosql_static_test_sql8)
}

func _gosql_static_test_sql1(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("select * from table \nwhere \n    ")
	{
		_outerCtx1 := ctx
		ctx = _outerCtx1.SubContext()
		{
			ctx.Set("i", 0)
			for LT(ctx.MustGet("i"), 10) {
				ctx.WriteSQL("\n            and id = ")
				ctx.AppendArg(ctx.MustGet("id"))
				ctx.AppendArg(ctx.MustGet("i"))
				ctx.WriteSQL(" \n            -- 数组的情况\n            and id in (")
				ctx.AppendArg(ctx.MustGet("ids"))
				ctx.WriteSQL(")\n            -- 直接输出的情况\n            and id = ")
				ctx.AppendRaw(ctx.MustGet("id"))
				ctx.WriteSQL("\n        ")
				ctx.Set("i", Add(ctx.MustGet("i"), 1))
			}
		}
		_query2 := ctx.BuildPtr()
		ctx = _outerCtx1
		ctx.CallFuncBlock("trim", _query2, "and")
		ctx.WriteQuery(_query2)
	}
	return nil
}

func _gosql_static_test_sql2(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("select * from table\nwhere id = 1\n    and name = ")
	{
		_v1, _ok1 := ctx.Get("name")
		if !_ok1 || !ToBool(_v1) {
			ctx.SkipCurrentLine()
		} else {
			ctx.AppendArg(_v1)
		}
	}
	ctx.WriteSQL("\n    and age = ")
	{
		_v2, _ok2 := ctx.Get("age")
		if !_ok2 || !ToBool(_v2) {
			ctx.SkipCurrentLine()
		} else {
			ctx.AppendArg(_v2)
		}
	}
	ctx.WriteSQL("\n    and id = ")
	{
		_v3, _ok3 := ctx.Get("id")
		if !_ok3 || !ToBool(_v3) {
			ctx.SkipCurrentLine()
		} else {
			ctx.AppendArg(_v3)
		}
	}
	ctx.WriteSQL("\n\n")
	{
		ctx.Set("i", 0)
		for LT(ctx.MustGet("i"), 2) {
			ctx.WriteSQL("\n    this is for item: id = ")
			ctx.AppendArg(ctx.MustGet("id"))
			ctx.WriteSQL("\n")
			ctx.Set("i", Add(ctx.MustGet("i"), 1))
		}
	}
	ctx.WriteSQL("\n\nfor end\n\n")
	if _forErr4 := Range(ctx.MustGet("ids"), func(_idx4, _val4 interface{}) error {
		ctx.Set("i", _idx4)
		ctx.Set("v", _val4)
		ctx.WriteSQL("\n    this is for item: id = ")
		ctx.AppendArg(ctx.MustGet("v"))
		ctx.WriteSQL("\n")
		return nil
	}); _forErr4 != nil { return _forErr4 }
	return nil
}

func _gosql_static_test_sql3(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("select * from \n-- 基础use\n")
	{
		_covers1 := make(map[string]func(*StaticContext) error)
		_coverFn2 := func(ctx *StaticContext) error {
			ctx.WriteSQL("\n        and id <> ")
			ctx.AppendArg(ctx.MustGet("id"))
			ctx.WriteSQL("\n    ")
			return nil
		}
		_covers1["a"] = _coverFn2
		_oldCovers3 := ctx.SwapCovers(_covers1)
		if _useErr4 := _gosql_static_test_sql4(ctx); _useErr4 != nil { ctx.SwapCovers(_oldCovers3); return _useErr4 }
		ctx.SwapCovers(_oldCovers3)
	}
	ctx.WriteSQL("\n-- usedefine的情况\n")
	{
		_covers5 := make(map[string]func(*StaticContext) error)
		_coverFn6 := func(ctx *StaticContext) error {
			ctx.WriteSQL("\n        and id = ")
			ctx.AppendArg(ctx.MustGet("id"))
			ctx.WriteSQL("\n    ")
			return nil
		}
		_covers5["b"] = _coverFn6
		_oldCovers7 := ctx.SwapCovers(_covers5)
		if _useErr8 := _gosql_static_test_sql4(ctx); _useErr8 != nil { ctx.SwapCovers(_oldCovers7); return _useErr8 }
		ctx.SwapCovers(_oldCovers7)
	}
	ctx.WriteSQL("\n\n")
	{
		_outerCtx9 := ctx
		ctx = _outerCtx9.SubContext()
		ctx.WriteSQL("select ok")
		_query10 := ctx.BuildPtr()
		ctx = _outerCtx9
		ctx.CallFuncBlock("GetName", _query10)
		ctx.WriteQuery(_query10)
	}
	return nil
}

func _gosql_static_test_sql4(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("select * from table\nwhere 1 = 1\n\n")
	{
		_outerCtx1 := ctx
		ctx = _outerCtx1.SubContext()
		if _forErr2 := Range(ctx.MustGet("ids"), func(_idx2, _val2 interface{}) error {
			ctx.Set("v", _val2)
			ctx.WriteSQL("\n        and id = ")
			ctx.AppendArg(ctx.MustGet("v"))
			ctx.WriteSQL("\n    ")
			return nil
		}); _forErr2 != nil { return _forErr2 }
		_query3 := ctx.BuildPtr()
		ctx = _outerCtx1
		ctx.CallFuncBlock("trim", _query3, "and")
		ctx.WriteQuery(_query3)
	}
	ctx.WriteSQL("\n\n")
	if _defErr4 := _gosql_static_test_sql4__a(ctx); _defErr4 != nil { return _defErr4 }
	return nil
}

func _gosql_static_test_sql5(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("name is ")
	ctx.AppendRaw(ctx.Call("GetName"))
	ctx.WriteSQL("\nid is ")
	ctx.AppendRaw(ctx.Call("GetId"))
	ctx.WriteSQL("\n\nand a = ")
	{
		_outerCtx1 := ctx
		ctx = _outerCtx1.SubContext()
		ctx.WriteSQL("select ok")
		_query2 := ctx.BuildPtr()
		ctx = _outerCtx1
		ctx.CallFuncBlock("Test", _query2)
		ctx.WriteQuery(_query2)
	}
	ctx.WriteSQL("\n\n")
	{
		_covers3 := make(map[string]func(*StaticContext) error)
		_oldCovers4 := ctx.SwapCovers(_covers3)
		if _useErr5 := _gosql_static_test_sql4__a(ctx); _useErr5 != nil { ctx.SwapCovers(_oldCovers4); return _useErr5 }
		ctx.SwapCovers(_oldCovers4)
	}
	return nil
}

func _gosql_static_test_sql6(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("select * from table\nwhere 1 = 1\n\n")
	{
		_outerCtx1 := ctx
		ctx = _outerCtx1.SubContext()
		if _forErr2 := Range(ctx.MustGet("ids"), func(_idx2, _val2 interface{}) error {
			ctx.Set("v", _val2)
			ctx.WriteSQL("\n        and id = ")
			ctx.AppendArg(ctx.MustGet("v"))
			ctx.WriteSQL("\n    ")
			return nil
		}); _forErr2 != nil { return _forErr2 }
		_query3 := ctx.BuildPtr()
		ctx = _outerCtx1
		ctx.CallFuncBlock("trim", _query3, "and")
		ctx.WriteQuery(_query3)
	}
	return nil
}

func _gosql_static_test_sql7(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("select * from ")
	ctx.AppendArg(ctx.Call("GetTable"))
	ctx.WriteSQL("\nwhere \n    1 = 1\n    and id = ")
	ctx.AppendArg(ctx.MustGet("id"))
	ctx.WriteSQL("\n    and name = ")
	ctx.AppendArg(ctx.Call("GetName"))
	ctx.WriteSQL("\n    and name = ")
	ctx.AppendRaw(ctx.MustGet("GetName"))
	ctx.WriteSQL("()\n\n")
	{
		_done1 := false
		if GT(ctx.MustGet("id"), 0) {
			ctx.WriteSQL("\n    and a = 1\n")
			_done1 = true
		}
		if !_done1 && false {
			ctx.WriteSQL("\n    and b = 2\n")
			_done1 = true
		}
		if !_done1 {
			ctx.WriteSQL("\n    and c = 3\n")
		}
	}
	ctx.WriteSQL("\n\n--# slot abc \n--# end\n\n")
	if _defErr2 := _gosql_static_test_sql7__abc(ctx); _defErr2 != nil { return _defErr2 }
	ctx.WriteSQL("\n\n--# trim ,\n--# end")
	return nil
}

func _gosql_static_test_sql7_5(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	ctx.WriteSQL("pre\n===\n\n")
	if _defErr1 := _gosql_static_test_sql7_5__abc(ctx); _defErr1 != nil { return _defErr1 }
	return nil
}

func _gosql_static_test_sql8(ctx *StaticContext) (retErr error) {
	defer ctx.Recover(&retErr)

	{
		_covers1 := make(map[string]func(*StaticContext) error)
		_coverFn2 := func(ctx *StaticContext) error {
			ctx.WriteSQL("\n        abc changed\n    ")
			return nil
		}
		_covers1["abc"] = _coverFn2
		_coverFn3 := func(ctx *StaticContext) error {
			ctx.WriteSQL("\n        d block changed\n    ")
			return nil
		}
		_covers1["abc.d"] = _coverFn3
		_oldCovers4 := ctx.SwapCovers(_covers1)
		if _useErr5 := _gosql_static_test_sql7_5(ctx); _useErr5 != nil { ctx.SwapCovers(_oldCovers4); return _useErr5 }
		ctx.SwapCovers(_oldCovers4)
	}
	ctx.WriteSQL("\n;\n\nselect * from table \nwhere\n")
	{
		_outerCtx6 := ctx
		ctx = _outerCtx6.SubContext()
		if _forErr7 := Range(ctx.MustGet("ids"), func(_idx7, _val7 interface{}) error {
			ctx.Set("v", _val7)
			ctx.WriteSQL("\n        and id = ")
			ctx.AppendArg(ctx.MustGet("v"))
			ctx.WriteSQL("\n    ")
			return nil
		}); _forErr7 != nil { return _forErr7 }
		_query8 := ctx.BuildPtr()
		ctx = _outerCtx6
		ctx.CallFuncBlock("Trim", _query8, "and")
		ctx.WriteQuery(_query8)
	}
	return nil
}

func _gosql_static_test_sql4__a__b(ctx *StaticContext) error {
	_fullPath := ctx.PushDefine("b")
	defer ctx.PopDefine()
	if _coverFn1 := ctx.GetCover(_fullPath, "b"); _coverFn1 != nil {
		return _coverFn1(ctx)
	}
	ctx.WriteSQL("\n\n    ")
	return nil
}

func _gosql_static_test_sql4__a(ctx *StaticContext) error {
	_fullPath := ctx.PushDefine("a")
	defer ctx.PopDefine()
	if _coverFn1 := ctx.GetCover(_fullPath, "a"); _coverFn1 != nil {
		return _coverFn1(ctx)
	}
	ctx.WriteSQL("\n    this is block a\n    and id = ")
	ctx.AppendArg(ctx.MustGet("id"))
	ctx.WriteSQL("\n    ")
	if _defErr2 := _gosql_static_test_sql4__a__b(ctx); _defErr2 != nil { return _defErr2 }
	ctx.WriteSQL("\n")
	return nil
}

func _gosql_static_test_sql7__abc__d(ctx *StaticContext) error {
	_fullPath := ctx.PushDefine("d")
	defer ctx.PopDefine()
	if _coverFn1 := ctx.GetCover(_fullPath, "d"); _coverFn1 != nil {
		return _coverFn1(ctx)
	}
	ctx.WriteSQL("\n        this is d block\n    ")
	return nil
}

func _gosql_static_test_sql7__abc(ctx *StaticContext) error {
	_fullPath := ctx.PushDefine("abc")
	defer ctx.PopDefine()
	if _coverFn1 := ctx.GetCover(_fullPath, "abc"); _coverFn1 != nil {
		return _coverFn1(ctx)
	}
	ctx.WriteSQL("\n    and id = ")
	ctx.AppendArg(ctx.MustGet("id"))
	ctx.WriteSQL("\n    and id2 = ")
	ctx.AppendRaw(ctx.MustGet("Id"))
	ctx.WriteSQL("\n\n    ")
	if _defErr2 := _gosql_static_test_sql7__abc__d(ctx); _defErr2 != nil { return _defErr2 }
	ctx.WriteSQL("\n")
	return nil
}

func _gosql_static_test_sql7_5__abc__d(ctx *StaticContext) error {
	_fullPath := ctx.PushDefine("d")
	defer ctx.PopDefine()
	if _coverFn1 := ctx.GetCover(_fullPath, "d"); _coverFn1 != nil {
		return _coverFn1(ctx)
	}
	ctx.WriteSQL("\n        this is d block\n    ")
	return nil
}

func _gosql_static_test_sql7_5__abc(ctx *StaticContext) error {
	_fullPath := ctx.PushDefine("abc")
	defer ctx.PopDefine()
	if _coverFn1 := ctx.GetCover(_fullPath, "abc"); _coverFn1 != nil {
		return _coverFn1(ctx)
	}
	ctx.WriteSQL("\n    and id = ")
	ctx.AppendArg(ctx.MustGet("id"))
	ctx.WriteSQL("\n    and id2 = ")
	ctx.AppendRaw(ctx.MustGet("Id"))
	ctx.WriteSQL("\n\n    ")
	if _defErr2 := _gosql_static_test_sql7_5__abc__d(ctx); _defErr2 != nil { return _defErr2 }
	ctx.WriteSQL("\n")
	return nil
}

